//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formula()
        {
            this.Item_group = new HashSet<Item_group>();
        }
    
        public int Formula_id { get; set; }
        public string Formula1 { get; set; }
        public string Formula_Author { get; set; }
        public string Formula_Create_Date { get; set; }
        public string Formula_Description { get; set; }
        public short Formula_Length_Factor { get; set; }
        public short Formula_Height_Factor { get; set; }
        public short Formula_Thickness_Factor { get; set; }
        public string Formula_Gab_Key { get; set; }
        public string Formula_Database { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_group> Item_group { get; set; }
    }
}
