//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Autocad_ConcerteList.ConcreteDB.DataBase
{
	public partial class Formula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formula()
        {
            this.Item_group = new HashSet<Item_group>();
        }
    
        public int Formula_id { get; set; }
        public string Formula1 { get; set; }
        public string Formula_Author { get; set; }
        public string Formula_Create_Date { get; set; }
        public string Formula_Description { get; set; }
        public short Formula_Length_Factor { get; set; }
        public short Formula_Height_Factor { get; set; }
        public short Formula_Thickness_Factor { get; set; }
        public string Formula_Gab_Key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_group> Item_group { get; set; }
    }
}
