//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_C_Formula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_C_Formula()
        {
            this.I_S_ItemGroup = new HashSet<I_S_ItemGroup>();
        }
    
        public decimal FormulaId { get; set; }
        public string FormulaValue { get; set; }
        public string FormulaAuthor { get; set; }
        public string FormulaCreateDate { get; set; }
        public string Description { get; set; }
        public short LengthFactor { get; set; }
        public short HeightFactor { get; set; }
        public short ThicknessFactor { get; set; }
        public string GabKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_S_ItemGroup> I_S_ItemGroup { get; set; }
    }
}
