//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_J_ItemSeries
    {
        public decimal ItemConstructionSeriesId { get; set; }
        public Nullable<decimal> ItemConstructionId { get; set; }
        public Nullable<decimal> SeriesId { get; set; }
    
        public virtual I_J_ItemConstruction I_J_ItemConstruction { get; set; }
        public virtual I_C_Series I_C_Series { get; set; }
    }
}
