//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_S_BalconyDoor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_S_BalconyDoor()
        {
            this.I_J_ItemConstruction = new HashSet<I_J_ItemConstruction>();
        }
    
        public decimal BalconyDoorId { get; set; }
        public string BalconyDoor { get; set; }
        public Nullable<decimal> SideId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_J_ItemConstruction> I_J_ItemConstruction { get; set; }
        public virtual I_S_Side I_S_Side { get; set; }
    }
}
