//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Autocad_ConcerteList.ConcreteDB.DataBase
{
	public partial class Item_construction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_construction()
        {
            this.Item_construction_colour = new HashSet<Item_construction_colour>();
            this.Item_construction_Product = new HashSet<Item_construction_Product>();
        }
    
        public int Item_construction_id { get; set; }
        public Nullable<int> Item_construction_id_access { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public Nullable<int> Item_group_id { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Thickness { get; set; }
        public Nullable<short> Formwork { get; set; }
        public Nullable<int> Balcony_door_id { get; set; }
        public Nullable<int> Balcony_cut_id { get; set; }
        public Nullable<int> Mount_element_id { get; set; }
        public Nullable<int> Prong_id { get; set; }
        public Nullable<short> FormworkMirror { get; set; }
        public string Electrics { get; set; }
        public Nullable<int> Step_height_id { get; set; }
        public Nullable<int> Steps { get; set; }
        public Nullable<int> First_step { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<float> Volume { get; set; }
    
        public virtual Item_modification BalconyCutModif { get; set; }
        public virtual Item_modification BalconyDoorModif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_construction_colour> Item_construction_colour { get; set; }
        public virtual Item_group Item_group { get; set; }
        public virtual Item_modification MountElementModif { get; set; }
        public virtual Item_modification ProngModif { get; set; }
        public virtual Item_modification StepHeightModif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_construction_Product> Item_construction_Product { get; set; }
    }
}
