//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_construction_Product
    {
        public int Item_construction_Product_id { get; set; }
        public Nullable<int> Item_construction_Product_id_access { get; set; }
        public int Item_construction_id { get; set; }
        public int Product_id { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual Item_construction Item_construction { get; set; }
        public virtual Product Product { get; set; }
    }
}
