//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_group()
        {
            this.Item_construction = new HashSet<Item_construction>();
        }
    
        public int Item_group_id { get; set; }
        public Nullable<int> Item_group_id_access { get; set; }
        public bool Item_group_usage { get; set; }
        public string Item_group1 { get; set; }
        public int Item_group_long_id { get; set; }
        public string Item_group_text_ISO { get; set; }
        public Nullable<int> Building_part_id { get; set; }
        public string Item_group_ISO { get; set; }
        public string Item_description { get; set; }
        public string Item_group_static { get; set; }
        public string Item_group_cut { get; set; }
        public string Item_group_layer { get; set; }
        public Nullable<bool> Formula_usage { get; set; }
        public Nullable<int> Formula_id { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
        public string Item_group_Grad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_construction> Item_construction { get; set; }
        public virtual Item_group_long Item_group_long { get; set; }
        public virtual Formula Formula { get; set; }
    }
}
