//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_construction_colour
    {
        public int Item_construction_colour_id { get; set; }
        public Nullable<int> Item_construction_colour_id_access { get; set; }
        public int Code_1C { get; set; }
        public string Article_1C { get; set; }
        public string Hand_mark { get; set; }
        public int Item_construction_id { get; set; }
        public Nullable<int> Item_colour_id { get; set; }
        public string Document_link { get; set; }
        public string Additional { get; set; }
    
        public virtual Item_colour Item_colour { get; set; }
        public virtual Item_construction Item_construction { get; set; }
    }
}
