//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_colour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_colour()
        {
            this.Item_construction_colour = new HashSet<Item_construction_colour>();
        }
    
        public int Item_colour_id { get; set; }
        public Nullable<int> Item_colour_id_access { get; set; }
        public string Item_colour1 { get; set; }
        public string Item_colour_hash { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_construction_colour> Item_construction_colour { get; set; }
    }
}
