//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Autocad_ConcerteList.ConcreteDB.DataBase
{
	public partial class Item_construction_Product
    {
        public int Item_construction_Product_id { get; set; }
        public Nullable<int> Item_construction_Product_id_access { get; set; }
        public int Item_construction_id { get; set; }
        public int Product_id { get; set; }
    
        public virtual Item_construction Item_construction { get; set; }
        public virtual Product Product { get; set; }
    }
}
