//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDMEntities : DbContext
    {
        public MDMEntities(DbConnection dbCon)
            : base(dbCon, true)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item_colour> Item_colour { get; set; }
        public virtual DbSet<Item_construction> Item_construction { get; set; }
        public virtual DbSet<Item_construction_colour> Item_construction_colour { get; set; }
        public virtual DbSet<Item_group> Item_group { get; set; }
        public virtual DbSet<Item_group_long> Item_group_long { get; set; }
        public virtual DbSet<Item_group_short> Item_group_short { get; set; }
        public virtual DbSet<Item_modification> Item_modification { get; set; }
        public virtual DbSet<Item_modification_type> Item_modification_type { get; set; }
        public virtual DbSet<Side> Side { get; set; }
        public virtual DbSet<Formula> Formula { get; set; }
        public virtual DbSet<Item_construction_Product> Item_construction_Product { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
