//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Item_construction_Product = new HashSet<Item_construction_Product>();
            this.Product11 = new HashSet<Product>();
        }
    
        public int Product_id { get; set; }
        public Nullable<int> Product_id_parent { get; set; }
        public string Product1 { get; set; }
        public Nullable<int> Product_id_access { get; set; }
        public System.Guid guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_construction_Product> Item_construction_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product11 { get; set; }
        public virtual Product Product2 { get; set; }
    }
}
