//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_C_Series
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_C_Series()
        {
            this.I_J_ItemSeries = new HashSet<I_J_ItemSeries>();
        }
    
        public decimal SeriesId { get; set; }
        public Nullable<decimal> SeriesParentId { get; set; }
        public string Series { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_J_ItemSeries> I_J_ItemSeries { get; set; }
    }
}
