//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_J_ItemConstruction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_J_ItemConstruction()
        {
            this.I_J_ItemSeries = new HashSet<I_J_ItemSeries>();
        }
    
        public decimal ItemConstructionId { get; set; }
        public string HandMarkNoColour { get; set; }
        public Nullable<decimal> ItemGroupId { get; set; }
        public Nullable<short> Lenght { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Thickness { get; set; }
        public Nullable<short> Formwork { get; set; }
        public Nullable<decimal> BalconyDoorId { get; set; }
        public Nullable<decimal> BalconyCutId { get; set; }
        public Nullable<short> FormworkMirror { get; set; }
        public string Electrics { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<float> Volume { get; set; }
    
        public virtual I_S_BalconyCut I_S_BalconyCut { get; set; }
        public virtual I_S_BalconyDoor I_S_BalconyDoor { get; set; }
        public virtual I_S_ItemGroup I_S_ItemGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_J_ItemSeries> I_J_ItemSeries { get; set; }
    }
}
