//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_S_ItemGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_S_ItemGroup()
        {
            this.I_J_ItemConstruction = new HashSet<I_J_ItemConstruction>();
        }
    
        public decimal ItemGroupId { get; set; }
        public bool ItemGroupUsage { get; set; }
        public string ItemGroup { get; set; }
        public Nullable<decimal> ItemGroupLongId { get; set; }
        public string ItemGroupTextISO { get; set; }
        public Nullable<decimal> BuildingPartId { get; set; }
        public string ItemGroupISO { get; set; }
        public string ItemDescription { get; set; }
        public string ItemGroupStatic { get; set; }
        public string ItemGroupCut { get; set; }
        public string ItemGroupLayer { get; set; }
        public Nullable<bool> HasFormula { get; set; }
        public Nullable<decimal> FormulaId { get; set; }
    
        public virtual I_C_Formula I_C_Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_J_ItemConstruction> I_J_ItemConstruction { get; set; }
    }
}
