//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocad_ConcerteList.Src.ConcreteDB.DataBase
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAPREntities : DbContext
    {
        public SAPREntities(DbConnection dbCon)
            : base(dbCon, true)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<I_C_Formula> I_C_Formula { get; set; }
        public virtual DbSet<I_J_ItemConstruction> I_J_ItemConstruction { get; set; }
        public virtual DbSet<I_J_ItemSeries> I_J_ItemSeries { get; set; }
        public virtual DbSet<I_S_BalconyCut> I_S_BalconyCut { get; set; }
        public virtual DbSet<I_S_BalconyDoor> I_S_BalconyDoor { get; set; }
        public virtual DbSet<I_S_ItemGroup> I_S_ItemGroup { get; set; }
        public virtual DbSet<I_C_Series> I_C_Series { get; set; }
    }
}
